# Generated by Django 3.1.7 on 2021-03-26 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AdoptaUnAmigo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='anuncio',
            old_name='description',
            new_name='descripcion',
        ),
        migrations.RenameField(
            model_name='anuncio',
            old_name='title',
            new_name='titulo',
        ),
    ]
