# Generated by Django 3.1.7 on 2021-04-20 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AdoptaUnAmigo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fotos_Anuncio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media', verbose_name='Image')),
                ('anuncio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdoptaUnAmigo.anuncio')),
            ],
        ),
    ]
