# Generated by Django 3.1.7 on 2021-04-21 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdoptaUnAmigo', '0002_fotos_anuncio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fotos_anuncio',
            name='image',
            field=models.ImageField(blank=True, default='media/Doggo-1.png', null=True, upload_to='images/', verbose_name='Image'),
        ),
    ]
