# Generated by Django 3.1.7 on 2021-04-21 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdoptaUnAmigo', '0003_auto_20210421_0008'),
    ]

    operations = [
        migrations.AddField(
            model_name='anuncio',
            name='animal',
            field=models.CharField(choices=[('perro', 'PERRO'), ('gato', 'GATO')], default='perro', max_length=6),
        ),
        migrations.AddField(
            model_name='anuncio',
            name='edad',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='anuncio',
            name='raza',
            field=models.CharField(default='.', max_length=20),
        ),
        migrations.AddField(
            model_name='anuncio',
            name='sexo',
            field=models.CharField(choices=[('macho', 'MACHO'), ('hembra', 'HEMBRA')], default='macho', max_length=6),
        ),
    ]
