# Generated by Django 3.1.7 on 2021-05-04 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('AdoptaUnAmigo', '0007_auto_20210426_1328'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoreinfoUsers',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('foto_perfil', models.ImageField(blank=True, default='media/Doggo-1.png', null=True, upload_to='images/', verbose_name='Image')),
                ('protectora', models.BooleanField(default=False)),
                ('biografia', models.TextField()),
                ('calle', models.CharField(max_length=50)),
                ('ciudad', models.CharField(max_length=50)),
            ],
        ),
    ]
