# Generated by Django 3.1.7 on 2021-05-04 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdoptaUnAmigo', '0009_auto_20210504_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moreinfousers',
            name='foto_perfil',
            field=models.ImageField(blank=True, default='images/Sin-foto-de-perfil-en-Facebook.jpg', null=True, upload_to='images/', verbose_name='Image'),
        ),
    ]
